### ISSUE TITLE
Where to put profile images so the website can serve them.

### ISSUE THREAD

**Issue by richardsc** [DalOceanDynamicsGroup/daloceandynamicsgroup.github.io#9]
I see @rcmusgrave added a `portraits/` folder inside of `members/`, but I think Hugo doesn't know to look there in the served site. I need to figure out where is the best place to put such images (I think it's in `static/`).

**Comment by richardsc** [comment]
Ah, the template for the member pages looks for images in `img/`, so they have to go into `static/img/portrait/` in order for the `"portrait/images.jpeg"` line to be correctly interpreted in the member markdown file.

**Comment by richardsc** [comment]
See e9dbb26fb4e300198906522

**Comment by rcmusgrave** [comment]
too fast! Thanks Clark :)
